Repository mt-mods/technic, pull requests merged in 2020-11, with the labels that each got.

#116 add minetest.get_current_modname() to fixture
  technic/spec/fixtures/minetest.lua
Labels: enhancement

#118 delete pull bot config
  .github/pull.yml
Labels: enhancement

#121 Fix digtron HV connector again (broken in #113)
  technic/machines/init.lua
Labels: bug

#110 Chests rework
  .luacheckrc
  technic_chests/chests.lua
  technic_chests/common.lua
  technic_chests/copper_chest.lua
  technic_chests/depends.txt
  technic_chests/digilines.lua
  technic_chests/formspec.lua
  technic_chests/gold_chest.lua
  technic_chests/init.lua
  technic_chests/inventory.lua
  technic_chests/iron_chest.lua
  technic_chests/mithril_chest.lua
  technic_chests/mod.conf
  technic_chests/register.lua
  technic_chests/silver_chest.lua
  technic_chests/textures/old/technic_chest_form_bg.png
  technic_chests/textures/old/technic_copper_chest_inventory.png
  technic_chests/textures/old/technic_form_bg.png
  technic_chests/textures/old/technic_gold_chest_inventory.png
  technic_chests/textures/old/technic_iron_chest_inventory.png
  technic_chests/textures/old/technic_main_inventory.png
  technic_chests/textures/old/technic_mithril_chest_inventory.png
  technic_chests/textures/old/technic_silver_chest_inventory.png
  technic_chests/textures/old/technic_wooden_chest_inventory.png
  technic_chests/textures/technic_chest_overlay_black.png
  technic_chests/textures/technic_chest_overlay_blue.png
  technic_chests/textures/technic_chest_overlay_brown.png
  technic_chests/textures/technic_chest_overlay_cyan.png
  technic_chests/textures/technic_chest_overlay_dark_green.png
  technic_chests/textures/technic_chest_overlay_dark_grey.png
  technic_chests/textures/technic_chest_overlay_green.png
  technic_chests/textures/technic_chest_overlay_grey.png
  technic_chests/textures/technic_chest_overlay_magenta.png
  technic_chests/textures/technic_chest_overlay_orange.png
  technic_chests/textures/technic_chest_overlay_pink.png
  technic_chests/textures/technic_chest_overlay_red.png
  technic_chests/textures/technic_chest_overlay_violet.png
  technic_chests/textures/technic_chest_overlay_white.png
  technic_chests/textures/technic_chest_overlay_yellow.png
  technic_chests/textures/technic_colorbutton0.png
  technic_chests/textures/technic_colorbutton1.png
  technic_chests/textures/technic_colorbutton10.png
  technic_chests/textures/technic_colorbutton11.png
  technic_chests/textures/technic_colorbutton12.png
  technic_chests/textures/technic_colorbutton13.png
  technic_chests/textures/technic_colorbutton14.png
  technic_chests/textures/technic_colorbutton2.png
  technic_chests/textures/technic_colorbutton3.png
  technic_chests/textures/technic_colorbutton4.png
  technic_chests/textures/technic_colorbutton5.png
  technic_chests/textures/technic_colorbutton6.png
  technic_chests/textures/technic_colorbutton7.png
  technic_chests/textures/technic_colorbutton8.png
  technic_chests/textures/technic_colorbutton9.png
  technic_chests/textures/technic_protector_overlay.png
Labels: enhancement

#129 Fix keys
  technic_chests/register.lua
Labels: bug

#126 Remove first 3 battery metadata read loops
  technic/machines/network.lua
  technic/machines/register/battery_box.lua
Labels: performance

#132 Improve self-contained injector
  technic/machines/other/injector.lua
Labels: enhancement, performance
