Repository mt-mods/technic, pull requests merged in 2021-11, with the labels that each got.

#234 Alias `technic:brass_block` CNC nodes
  technic_cnc/materials/init.lua
Labels: Bug fix

#208 Extended Mineunit tests
  technic/spec/building_spec.lua
  technic/spec/cnc_spec.lua
  technic/spec/fixtures/default.lua
  technic/spec/fixtures/mesecons.lua
  technic/spec/fixtures/network.lua
  technic/spec/fixtures/pipeworks.lua
  technic/spec/fixtures/technic.conf
  technic/spec/fixtures/technic.lua
  technic/spec/fixtures/technic_cnc.lua
  technic/spec/fixtures/technic_worldgen.lua
  technic/spec/hv_network_spec.lua
  technic/spec/lv_network_spec.lua
  technic/spec/mineunit.conf
  technic/spec/network_spec.lua
  technic/spec/nodes_spec.lua
  technic/spec/supply_converter_spec.lua
  technic_cnc/spec/digilines_spec.lua
Labels: Enhancement, Documentation

#240 Fix sulfur block recipes
  technic_worldgen/crafts.lua
Labels: Bug fix

#243 Wrench update
  wrench/init.lua
  wrench/nodes/technic.lua
  wrench/nodes/technic_chests.lua
  wrench/nodes/technic_cnc.lua
Labels: Enhancement, Blocked

#247 Wrench rewrite
  wrench/api.lua
  wrench/functions.lua
  wrench/init.lua
  wrench/legacy.lua
  wrench/mod.conf
  wrench/nodes/default.lua
  wrench/nodes/digtron.lua
  wrench/nodes/drawers.lua
  wrench/nodes/technic.lua
  wrench/nodes/technic_chests.lua
  wrench/nodes/technic_cnc.lua
  wrench/tool.lua
Labels: Enhancement, Testing needed

#252 Update URLs for `pipeworks`, `basic_materials` and `unifieddyes`
  README.md
  generate-mtinfo.sh
  integration-test.sh
  technic_cnc/pipeworks.lua
Labels: Bug fix
