Repository mt-mods/technic, pull requests merged in 2021-08, with the labels that each got.

#198 Add alloying recipes for cheaper digiline cables
  technic/machines/HV/cables.lua
  technic/machines/LV/cables.lua
  technic/machines/MV/cables.lua
  technic/machines/register/alloy_recipes.lua
Labels: Enhancement

#202 Few small cleanup changes
  .textures/alternate/technic_concrete_block.png
  technic/spec/fixtures/minetest.cfg
  technic/spec/fixtures/minetest.conf
Labels: Cleanup

#205 Disable repair recipes for crystals and batteries
  technic/items.lua
  technic/machines/register/battery_box.lua
Labels: Bug fix
