Repository mt-mods/technic, pull requests merged in 2021-03, with the labels that each got.

#157 remove unused "technic.smelt_item"
  technic/machines/register/common.lua
Labels: Cleanup

#162 Supply converter protection
  technic/machines/supply_converter.lua
  technic/spec/supply_converter_spec.lua
Labels: Bug

#165 add mtinfo generate workflow
  .github/workflows/mtinfo.yml
  README.md
  generate-mtinfo.sh
Labels: WIP

#167 add moreblocks to mtinfo mods
  generate-mtinfo.sh
Labels: Enhancement

#169 add moreblocks.stairsplus_in_creative_inventory to mtinfo config, dec…
  generate-mtinfo.sh
Labels: Documentation, Enhancement
