Repository mt-mods/technic, pull requests merged in 2022-06, with the labels that each got.

#270 fix typo in readme
  README.md
Labels: Documentation

#275 Compatibility for technic_set_charge/technic_get_charge
  technic/doc/api.md
  technic/helpers.lua
  technic/machines/register/battery_box.lua
  technic/register.lua
Labels: Enhancement, Compatibility

#276 Tool compatibility shims
  technic/machines/compat/tools.lua
  technic/spec/fixtures/old_powertool.lua
  technic/spec/tools_compatibility_spec.lua
  technic/spec/tools_spec.lua
Labels: Compatibility
