Repository mt-mods/technic, pull requests merged in 2022-11, with the labels that each got.

#288 Quarry 3.0
  technic/config.lua
  technic/machines/HV/quarry.lua
  technic/textures/technic_line_particle.png
  technic/textures/technic_quarry_bottom.png
Labels: Enhancement, Performance

#289 Translation fixes and improvements
  technic/chatcommands.lua
  technic/init.lua
  technic/locale/technic.de.tr
  technic/locale/technic.es.tr
  technic/locale/technic.fr.tr
  technic/locale/technic.it.tr
  technic/locale/technic.pl.tr
  technic/locale/technic.pt_BR.tr
  technic/locale/technic.zh_CN.tr
  technic/locale/template.txt
  technic/machines/HV/forcefield.lua
  technic/machines/HV/nuclear_reactor.lua
  technic/machines/HV/quarry.lua
  technic/machines/LV/geothermal.lua
  technic/machines/LV/music_player.lua
  technic/machines/LV/water_mill.lua
  technic/machines/MV/hydro_turbine.lua
  technic/machines/init.lua
  technic/machines/other/anchor.lua
  technic/machines/power_monitor.lua
  technic/machines/register/battery_box.lua
  technic/machines/register/generator.lua
  technic/machines/supply_converter.lua
  technic/machines/switching_station.lua
  technic/machines/switching_station_globalstep.lua
  technic/tools/prospector.lua
Labels: Translations

#290 Remove frames, power radiator and lighting
  .textures/unused/technic_frame.png
  .textures/unused/technic_homedecor_glowlight_cube_white_sides.png
  .textures/unused/technic_homedecor_glowlight_cube_white_tb.png
  .textures/unused/technic_homedecor_glowlight_cube_yellow_sides.png
  .textures/unused/technic_homedecor_glowlight_cube_yellow_tb.png
  .textures/unused/technic_homedecor_glowlight_thick_white_sides.png
  .textures/unused/technic_homedecor_glowlight_thick_yellow_sides.png
  .textures/unused/technic_homedecor_glowlight_thin_white_sides.png
  .textures/unused/technic_homedecor_glowlight_thin_yellow_sides.png
  .textures/unused/technic_homedecor_glowlight_white_tb.png
  .textures/unused/technic_homedecor_glowlight_yellow_tb.png
  technic/config.lua
  technic/machines/MV/init.lua
  technic/machines/MV/lighting.lua
  technic/machines/MV/power_radiator.lua
  technic/machines/other/frames.lua
  technic/machines/other/init.lua
Labels: Cleanup

#293 japanese translation
  concrete/locale/ja.txt
  extranodes/locale/ja.txt
  technic_chests/locale/ja.txt
  wrench/locale/ja.txt
Labels: Translations

#294 add `technic.register_cable_tier(nodename, tier)`
  technic/doc/api.md
  technic/machines/register/cables.lua
Labels: Compatibility
