Repository mt-mods/technic, pull requests merged in 2023-09, with the labels that each got.

#326 Update luacheck
  .github/workflows/luacheck.yml
  technic/tools/sonic_screwdriver.lua
Labels: Enhancement

#325 Fix LED crafting recipe
  technic/machines/LV/led.lua
Labels: Bug fix

#323 MineClone/MineClonia compatibility for technic worldgen
  .luacheckrc
  technic_worldgen/init.lua
  technic_worldgen/mod.conf
  technic_worldgen/nodes.lua
  technic_worldgen/oregen.lua
  technic_worldgen/rubber.lua
Labels: Enhancement, Compatibility
