Repository mt-mods/technic, pull requests merged in 2023-07, with the labels that each got.

#315 Quarry y-offset and fixes
  technic/machines/HV/quarry.lua
Labels: Enhancement

#316 Limit quarry y-offset by max depth
  technic/machines/HV/quarry.lua
Labels: Bug fix

#317 Add energy demand to machine infotexts
  technic/locale/technic.de.tr
  technic/locale/technic.es.tr
  technic/locale/technic.fr.tr
  technic/locale/technic.it.tr
  technic/locale/technic.pl.tr
  technic/locale/technic.pt_BR.tr
  technic/locale/technic.zh_CN.tr
  technic/locale/template.txt
  technic/machines/HV/forcefield.lua
  technic/machines/HV/quarry.lua
  technic/machines/LV/lamp.lua
  technic/machines/LV/led.lua
  technic/machines/LV/music_player.lua
  technic/machines/MV/tool_workshop.lua
  technic/machines/register/machine_base.lua
Labels: Enhancement, WIP
