Repository mt-mods/technic, pull requests merged in 2024-04, with the labels that each got.

#357 Check fuel inventory is empty before digging machine
  technic/machines/register/common.lua
Labels: Bug fix

#359 quarry_dig_above_nodes removed
  README.md
  technic/spec/fixtures/technic.conf
Labels: Cleanup

#358 Fix cable plate placing on several-blocks nodes
  technic/machines/register/cables.lua
Labels: Bug fix

#361 use `mtt` action for integration tests
  .github/workflows/integration-test.yml
  .github/workflows/mtt.yml
  .test/Dockerfile
  .test/minetest.conf
  README.md
  docker-compose.yml
  technic/init.lua
  technic/mtt.lua
  technic/registered_nodes.txt
Labels: Enhancement, Cleanup
