Repository mt-mods/technic, pull requests merged in 2024-01, with the labels that each got.

#335 Add ExchangeClone support.
  .luacheckrc
  technic/machines/register/recipes.lua
  technic/mod.conf
Labels: Enhancement, Compatibility

#339 Remove `mtinfo` workflow
  .github/workflows/mtinfo.yml
  README.md
  generate-mtinfo.sh
Labels: Cleanup

#328 MineClone/MineClonia compatibility for technic core
  .luacheckrc
  technic/crafts.lua
  technic/init.lua
  technic/items.lua
  technic/machines/HV/forcefield.lua
  technic/machines/HV/nuclear_reactor.lua
  technic/machines/HV/quarry.lua
  technic/machines/LV/alloy_furnace.lua
  technic/machines/LV/cables.lua
  technic/machines/LV/compressor.lua
  technic/machines/LV/electric_furnace.lua
  technic/machines/LV/generator.lua
  technic/machines/LV/geothermal.lua
  technic/machines/LV/grinder.lua
  technic/machines/LV/lamp.lua
  technic/machines/LV/led.lua
  technic/machines/LV/music_player.lua
  technic/machines/LV/solar_panel.lua
  technic/machines/LV/water_mill.lua
  technic/machines/MV/hydro_turbine.lua
  technic/machines/MV/tool_workshop.lua
  technic/machines/MV/wind_mill.lua
  technic/machines/other/anchor.lua
  technic/machines/other/coal_alloy_furnace.lua
  technic/machines/other/coal_furnace.lua
  technic/machines/other/constructor.lua
  technic/machines/other/injector.lua
  technic/machines/power_monitor.lua
  technic/machines/register/alloy_recipes.lua
  technic/machines/register/battery_box.lua
  technic/machines/register/cables.lua
  technic/machines/register/centrifuge_recipes.lua
  technic/machines/register/common.lua
  technic/machines/register/compressor_recipes.lua
  technic/machines/register/freezer_recipes.lua
  technic/machines/register/generator.lua
  technic/machines/register/grinder_recipes.lua
  technic/machines/register/grindings.lua
  technic/machines/register/machine_base.lua
  technic/machines/register/recipes.lua
  technic/machines/register/solar_array.lua
  technic/machines/supply_converter.lua
  technic/machines/switching_station.lua
  technic/materials.lua
  technic/mod.conf
  technic/radiation.lua
  technic/spec/fixtures/network.lua
  technic/tools/cans.lua
  technic/tools/chainsaw.lua
  technic/tools/flashlight.lua
  technic/tools/mining_drill.lua
  technic/tools/mining_lasers.lua
  technic/tools/prospector.lua
  technic/tools/sonic_screwdriver.lua
  technic/tools/tree_tap.lua
  technic_worldgen/crafts.lua
  technic_worldgen/init.lua
Labels: Compatibility

#338 Rewrite recipe code and add group support
  .luacheckrc
  technic/machines/register/grindings.lua
  technic/machines/register/recipes.lua
  technic/materials.lua
  technic/mod.conf
Labels: Enhancement, Performance, Bug fix, Compatibility

#340 ci testing overhaul
  .github/workflows/integration-test.yml
  .test/Dockerfile
  .test/minetest.conf
  docker-compose.yml
  modpack.conf
Labels: Cleanup
