Repository mt-mods/technic, pull requests merged in 2024-09, with the labels that each got.

#375 Add settingtypes.txt for technic_cnc
  technic_cnc/settingtypes.txt
Labels: Enhancement, Documentation

#377 Apply low pass filter to sonic screwdriver sound
  technic/sounds/technic_sonic_screwdriver.ogg
  technic/tools/sonic_screwdriver.lua
Labels: Enhancement

#379 Replace removed function `pipeworks.string_startswith`
  technic_cnc/pipeworks.lua
Labels: Bug fix, Compatibility

#380 Fix wrong texts for uranium elements
  technic/locale/technic.fr.tr
Labels: Bug fix
