Repository mt-mods/technic, pull requests merged in 2025-03, with the labels that each got.

#407 Fix shading on CNC shape models
  technic_cnc/models/technic_cnc_cylinder.obj
  technic_cnc/models/technic_cnc_cylinder_horizontal.obj
  technic_cnc/models/technic_cnc_innercorner.obj
  technic_cnc/models/technic_cnc_innercorner_upsdown.obj
  technic_cnc/models/technic_cnc_two_curved_edge.obj
Labels: Bug fix

#399 API v1 to v2 shim: follow spec with shallow copy
  technic/machines/compat/api.lua
Labels: Bug, Compatibility

#402 Drop legacy.lua
  technic/init.lua
  technic/legacy.lua
  technic/machines/MV/generator.lua
Labels: Cleanup
